python binomial.py
python genome.py
python gibbs.py
python godata.py
python guide.py
python ml.py
python phylo.py
python prob.py
python rcdict.py
python sam.py
python seqdata.py
python sequence.py
python spred.py
python sstruct.py
python stats.py
python sym.py
python webservice.py
python wordcount.py
rm *.pyc
